// TOEIC頻出単語データ
// w: 単語 / m: 意味 / ex: 例文 / exJa: 例文の和訳 / tip: 覚え方・用途 / lv: 1=基礎(〜600) 2=中級(〜730) 3=上級(860〜)
const WORDS = [
  // ===== レベル1: 基礎（〜600点） =====
  {w:"invoice", m:"請求書", ex:"Please pay the invoice by the end of the month.", exJa:"月末までに請求書のお支払いをお願いします。", tip:"billと違い企業間取引の請求書。Part 7の請求書文書で頻出。「送り状」の意味もある。", lv:1},
  {w:"appointment", m:"（面会の）約束、予約", ex:"I have an appointment with a client at three.", exJa:"3時に取引先と会う約束があります。", tip:"「アポ」の語源。病院の予約にも使う（席や部屋の予約はreservation）。", lv:1},
  {w:"schedule", m:"予定表、スケジュール", ex:"The meeting is scheduled for Monday.", exJa:"会議は月曜日に予定されています。", tip:"be scheduled for 〜「〜に予定されている」の形で頻出。ahead of schedule＝予定より早く。", lv:1},
  {w:"attend", m:"出席する", ex:"More than 100 people attended the conference.", exJa:"100人以上がその会議に出席した。", tip:"attend a meetingのように前置詞なしで使う。attendee＝出席者もセットで覚える。", lv:1},
  {w:"confirm", m:"確認する", ex:"I'm writing to confirm my reservation.", exJa:"予約の確認のためにご連絡しています。", tip:"ビジネスメールの定番動詞。confirmation number＝予約確認番号。", lv:1},
  {w:"deliver", m:"配達する", ex:"Your package will be delivered tomorrow.", exJa:"お荷物は明日配達されます。", tip:"名詞はdelivery（配達）。deliver a speech「スピーチを行う」の意味もPart 5で狙われる。", lv:1},
  {w:"employee", m:"従業員", ex:"All employees must wear ID badges.", exJa:"全従業員はIDバッジの着用が必要です。", tip:"employ（雇う）+ ee（〜される人）。employer（雇い主）との対比で覚える。", lv:1},
  {w:"customer", m:"顧客、（店の）客", ex:"The store offers discounts to regular customers.", exJa:"その店は常連客に割引を提供している。", tip:"custom（習慣）から「いつも来る人」。customer satisfaction＝顧客満足。", lv:1},
  {w:"order", m:"注文（する）", ex:"I'd like to place an order for ten chairs.", exJa:"椅子を10脚注文したいのですが。", tip:"place an order＝注文する。out of order＝故障中もPart 1・2で頻出。", lv:1},
  {w:"receipt", m:"領収書、レシート", ex:"Keep your receipt for a refund.", exJa:"返金には領収書を保管してください。", tip:"発音は「リシート」（pは読まない）。receive（受け取る）の名詞形。", lv:1},
  {w:"refund", m:"返金（する）", ex:"You can get a full refund within 30 days.", exJa:"30日以内なら全額返金が受けられます。", tip:"re（戻す）+ fund（資金）。full refund＝全額返金の形で頻出。", lv:1},
  {w:"available", m:"利用可能な、都合がつく", ex:"Is the manager available now?", exJa:"部長は今、手が空いていますか？", tip:"人にも物にも使える万能語。「入手できる・空いている・都合がつく」は全部これ。", lv:1},
  {w:"purchase", m:"購入する、購入品", ex:"Thank you for your recent purchase.", exJa:"この度はお買い上げありがとうございます。", tip:"buyのフォーマル版。名詞でも動詞でも使う。proof of purchase＝購入証明。", lv:1},
  {w:"provide", m:"提供する", ex:"We provide free shipping on all orders.", exJa:"全てのご注文で送料無料をご提供します。", tip:"provide A with B＝AにBを提供する。語法問題の定番。", lv:1},
  {w:"offer", m:"申し出る、（条件を）提示する", ex:"They offered me the position.", exJa:"彼らは私にその職を打診してくれた。", tip:"名詞では「割引・提案」。job offer＝採用通知、special offer＝特別セール。", lv:1},
  {w:"contract", m:"契約（書）", ex:"Both parties signed the contract.", exJa:"両者が契約書に署名した。", tip:"sign a contract＝契約を結ぶ。con（共に）+ tract（引く）→互いに取り決める。", lv:1},
  {w:"department", m:"部署、部門", ex:"She works in the sales department.", exJa:"彼女は営業部で働いている。", tip:"〜departmentで部署名になる。department store＝百貨店（部門ごとの店）。", lv:1},
  {w:"manager", m:"部長、責任者", ex:"Please contact the store manager.", exJa:"店長にご連絡ください。", tip:"TOEICでは「部長・店長・責任者」。hiring manager＝採用担当者。", lv:1},
  {w:"product", m:"製品", ex:"This product comes with a two-year warranty.", exJa:"この製品には2年保証が付いています。", tip:"produce（生産する）の名詞。productive＝生産的な、も併せて覚える。", lv:1},
  {w:"announce", m:"公表する、発表する", ex:"The company announced a new product line.", exJa:"その会社は新製品ラインを発表した。", tip:"announcement＝お知らせは、Part 4のアナウンス問題の定番語。", lv:1},
  {w:"apply", m:"申し込む、応募する", ex:"She applied for the marketing position.", exJa:"彼女はマーケティング職に応募した。", tip:"apply for 〜＝に応募する。applicant＝応募者、application＝応募（書類）。", lv:1},
  {w:"hire", m:"雇う", ex:"We're hiring additional staff for the summer.", exJa:"夏に向けて追加スタッフを雇っています。", tip:"new hire＝新入社員という名詞用法もある。英国では「（車などを）借りる」の意味も。", lv:1},
  {w:"salary", m:"給料", ex:"The job offers a competitive salary.", exJa:"その仕事は他社に負けない給料を提示している。", tip:"月給・年俸のイメージ（時給はwage）。competitive salaryは求人広告の決まり文句。", lv:1},
  {w:"warranty", m:"（品質）保証、保証書", ex:"The warranty covers parts and labor.", exJa:"保証は部品代と作業代をカバーします。", tip:"under warranty＝保証期間内。guaranteeとほぼ同義だが、書類はwarranty。", lv:1},
  {w:"shipment", m:"発送、出荷（品）", ex:"The shipment will arrive on Friday.", exJa:"発送品は金曜日に到着予定です。", tip:"ship＝発送する（船以外でも使う）。shipping＝送料・発送。", lv:1},
  {w:"supply", m:"供給、備品", ex:"Office supplies are stored in the cabinet.", exJa:"事務用品はキャビネットに保管されています。", tip:"office supplies＝事務用品は超頻出。supplier＝納入業者。", lv:1},
  {w:"repair", m:"修理する", ex:"The copier needs to be repaired.", exJa:"コピー機は修理が必要です。", tip:"Part 1で「修理中の人」の描写に頻出。fixよりフォーマル。", lv:1},
  {w:"install", m:"設置する、インストールする", ex:"New software will be installed on all computers.", exJa:"全てのPCに新しいソフトがインストールされます。", tip:"機械・設備の「設置」にも使う。installation＝設置（工事）。", lv:1},
  {w:"submit", m:"提出する", ex:"Please submit your report by Friday.", exJa:"金曜日までに報告書を提出してください。", tip:"sub（下に）+ mit（送る）→差し出す。submit A to Bの形で頻出。", lv:1},
  {w:"complete", m:"完了する、（書類に）記入する", ex:"Please complete this form.", exJa:"この用紙にご記入ください。", tip:"「完了する」だけでなく「記入する」（＝fill out）の意味がTOEICでは重要。", lv:1},
  {w:"colleague", m:"同僚", ex:"I discussed the plan with my colleagues.", exJa:"同僚たちとその計画について話し合った。", tip:"co（共に）+ league（仲間）。coworkerと同義。アクセントは前（カ）にある。", lv:1},
  {w:"client", m:"取引先、依頼人", ex:"The lawyer met with a client.", exJa:"その弁護士は依頼人と面会した。", tip:"弁護士・コンサルなど専門サービスの顧客。小売店の客はcustomer。", lv:1},

  // ===== レベル2: 中級（〜730点） =====
  {w:"accommodate", m:"収容する、（要望に）応える", ex:"The hall can accommodate 300 guests.", exJa:"そのホールは300人の客を収容できます。", tip:"「収容する」と「（要望に）応える」の2つの意味。accommodations＝宿泊施設。", lv:2},
  {w:"itinerary", m:"旅程（表）", ex:"I'll send you the itinerary for your business trip.", exJa:"出張の旅程表をお送りします。", tip:"出張・旅行関連の文書で定番。読み方は「アイティネラリー」。", lv:2},
  {w:"reimburse", m:"（経費を）払い戻す", ex:"Employees will be reimbursed for travel expenses.", exJa:"従業員は出張費の払い戻しを受けられます。", tip:"経費精算の話題で頻出。re（戻す）+ burse（財布）。reimbursement＝払い戻し。", lv:2},
  {w:"expire", m:"期限が切れる", ex:"My passport expires next month.", exJa:"パスポートは来月期限が切れます。", tip:"expiration date＝有効期限。クーポンや契約の話題で頻出。", lv:2},
  {w:"negotiate", m:"交渉する", ex:"We negotiated a better price with the supplier.", exJa:"納入業者ともっと良い価格を交渉した。", tip:"日本語の「ネゴ」の語源。negotiation＝交渉。", lv:2},
  {w:"postpone", m:"延期する", ex:"The event was postponed due to rain.", exJa:"イベントは雨のため延期された。", tip:"post（後に）+ pone（置く）。put offと同義。Part 2の応答で頻出。", lv:2},
  {w:"inquiry", m:"問い合わせ", ex:"Thank you for your inquiry about our services.", exJa:"弊社サービスへのお問い合わせありがとうございます。", tip:"inquire＝問い合わせる。ビジネスメールの冒頭の定番フレーズ。", lv:2},
  {w:"estimate", m:"見積もり、見積もる", ex:"Could you give me an estimate for the repairs?", exJa:"修理の見積もりをいただけますか？", tip:"名詞「見積もり」と動詞「見積もる」の両方で使う。estimated time of arrival＝到着予定時刻。", lv:2},
  {w:"merchandise", m:"商品", ex:"All merchandise is 20% off this week.", exJa:"今週は全商品20％引きです。", tip:"集合名詞で数えられない。merchant（商人）の関連語。goodsと同義。", lv:2},
  {w:"inventory", m:"在庫、棚卸し", ex:"We're taking inventory this weekend.", exJa:"今週末に棚卸しをします。", tip:"take inventory＝棚卸しをする。在庫はstockとも言う。", lv:2},
  {w:"facility", m:"施設、設備", ex:"The hotel has excellent fitness facilities.", exJa:"そのホテルには素晴らしいフィットネス施設があります。", tip:"複数形facilitiesでよく使う。「設備・施設」を表す万能語。", lv:2},
  {w:"agenda", m:"議題、協議事項", ex:"The first item on the agenda is the budget.", exJa:"議題の最初の項目は予算です。", tip:"item on the agenda＝議題の項目。会議文書（Part 7）の定番。", lv:2},
  {w:"quarterly", m:"四半期の", ex:"The quarterly report is due next week.", exJa:"四半期報告書の期限は来週です。", tip:"quarter＝4分の1→3か月。annually（年1回）、monthly（月1回）とセットで覚える。", lv:2},
  {w:"revenue", m:"収益、歳入", ex:"The company's revenue increased by 15%.", exJa:"会社の収益は15％増加した。", tip:"売上高・総収入のこと。profit（利益）との違いに注意。増減の話題で頻出。", lv:2},
  {w:"budget", m:"予算", ex:"We need to stay within the budget.", exJa:"予算内に収める必要があります。", tip:"within the budget＝予算内で。budget cut＝予算削減。", lv:2},
  {w:"extend", m:"延長する", ex:"They extended the deadline by one week.", exJa:"締め切りが1週間延長された。", tip:"ex（外へ）+ tend（伸ばす）。extension＝延長・内線番号。", lv:2},
  {w:"renovate", m:"改装する", ex:"The office is being renovated.", exJa:"オフィスは改装中です。", tip:"re（再び）+ nov（新しく）。renovation＝改装工事はPart 3・4の頻出テーマ。", lv:2},
  {w:"recruit", m:"（人材を）募集する", ex:"The company is recruiting engineers.", exJa:"その会社はエンジニアを募集している。", tip:"日本語の「リクルート」そのまま。recruiter＝採用担当者。", lv:2},
  {w:"retire", m:"退職する、引退する", ex:"He retired after 30 years with the company.", exJa:"彼は30年勤めた会社を退職した。", tip:"retirement party＝退職記念パーティーはTOEIC頻出イベント。", lv:2},
  {w:"promote", m:"昇進させる、販売促進する", ex:"She was promoted to sales manager.", exJa:"彼女は営業部長に昇進した。", tip:"「昇進させる」と「販促する」の2つ。promotion＝昇進・販促キャンペーン。", lv:2},
  {w:"transfer", m:"異動させる、移す", ex:"He was transferred to the Osaka branch.", exJa:"彼は大阪支店に異動になった。", tip:"電話の「おつなぎします」（transfer your call）や乗り換えにも使う。", lv:2},
  {w:"evaluate", m:"評価する", ex:"Managers evaluate employee performance annually.", exJa:"管理職は毎年従業員の業績を評価する。", tip:"e + valu（価値）+ ate→価値を測る。performance evaluation＝人事評価。", lv:2},
  {w:"implement", m:"実施する、導入する", ex:"The new policy will be implemented in April.", exJa:"新しい方針は4月に実施される。", tip:"計画・制度を「実行に移す」こと。implementation＝実施。", lv:2},
  {w:"launch", m:"（新商品を）発売する、開始する", ex:"The company will launch a new smartphone.", exJa:"その会社は新しいスマートフォンを発売する。", tip:"ロケットの「打ち上げ」から新商品の「発売」へ。product launch＝新商品発売。", lv:2},
  {w:"expand", m:"拡大する", ex:"The firm plans to expand into Asia.", exJa:"その会社はアジアへの進出を計画している。", tip:"expansion＝拡大。expend（費やす）とのスペル違いに注意。", lv:2},
  {w:"distribute", m:"配布する、流通させる", ex:"Handouts will be distributed before the seminar.", exJa:"資料はセミナーの前に配布されます。", tip:"dis（別々に）+ tribute（与える）。distributor＝販売代理店。", lv:2},
  {w:"manufacture", m:"製造する", ex:"The parts are manufactured in Vietnam.", exJa:"その部品はベトナムで製造されている。", tip:"manu（手）+ fact（作る）。manufacturer＝メーカー・製造業者は超頻出。", lv:2},
  {w:"subscribe", m:"定期購読する", ex:"Subscribe to our newsletter for updates.", exJa:"最新情報はニュースレターをご購読ください。", tip:"subscribe to 〜の形で使う。subscription＝定期購読（サブスク）。", lv:2},
  {w:"attach", m:"添付する", ex:"I've attached the file to this email.", exJa:"このメールにファイルを添付しました。", tip:"attached file＝添付ファイル。メール問題の定番。反意語はdetach。", lv:2},
  {w:"notify", m:"通知する", ex:"We will notify you of the results by email.", exJa:"結果はメールでお知らせします。", tip:"notify A of B＝AにBを知らせる。notification＝通知。", lv:2},
  {w:"comply", m:"（規則に）従う", ex:"All buildings must comply with safety regulations.", exJa:"全ての建物は安全基準に従わなければならない。", tip:"comply with 〜＝に従う。compliance＝法令遵守（コンプラ）。", lv:2},
  {w:"feature", m:"特徴、目玉にする", ex:"The new model features a larger screen.", exJa:"新モデルはより大きな画面が特徴です。", tip:"動詞「〜を特徴とする・目玉にする」が重要。featured product＝注目商品。", lv:2},

  // ===== レベル3: 上級（860点〜） =====
  {w:"lucrative", m:"儲かる、利益の大きい", ex:"They signed a lucrative contract.", exJa:"彼らは利益の大きい契約を結んだ。", tip:"profitableの上位語彙。lucrative deal / marketなどお金の話題で登場。", lv:3},
  {w:"meticulous", m:"細心の、几帳面な", ex:"She is meticulous about details.", exJa:"彼女は細部まで非常に几帳面だ。", tip:"求人や人物評価で登場。attention to detail（細部への注意）とセットで覚える。", lv:3},
  {w:"endorse", m:"支持する、推奨する", ex:"The product is endorsed by famous athletes.", exJa:"その製品は有名アスリートに推奨されている。", tip:"有名人による「推薦・宣伝」や案の「支持」。小切手の裏書きが原義。", lv:3},
  {w:"procurement", m:"調達", ex:"He works in the procurement department.", exJa:"彼は調達部門で働いている。", tip:"procure＝調達する。purchasing（購買）のフォーマル版。", lv:3},
  {w:"remuneration", m:"報酬", ex:"The position offers generous remuneration.", exJa:"その職は高額の報酬を提示している。", tip:"給与・報酬のフォーマル語。求人広告（Part 7）で登場。", lv:3},
  {w:"discrepancy", m:"不一致、食い違い", ex:"There is a discrepancy between the two reports.", exJa:"2つの報告書の間に食い違いがある。", tip:"請求額や在庫数の「不一致」はTOEICの定番トラブル。", lv:3},
  {w:"contingency", m:"不測の事態", ex:"We need a contingency plan.", exJa:"不測の事態への対応策が必要だ。", tip:"contingency plan＝緊急時対応計画、の形で覚える。", lv:3},
  {w:"streamline", m:"合理化する、効率化する", ex:"The company streamlined its ordering process.", exJa:"会社は注文プロセスを効率化した。", tip:"stream（流れ）+ line→流線形に→無駄をなくす。業務改善の話題で頻出。", lv:3},
  {w:"unprecedented", m:"前例のない", ex:"The store saw unprecedented demand.", exJa:"その店はかつてない需要に見舞われた。", tip:"un + precedent（前例）+ ed。「前例のない成長・需要」などプラスの文脈が多い。", lv:3},
  {w:"provisional", m:"暫定的な", ex:"A provisional schedule will be sent this week.", exJa:"暫定スケジュールが今週送られます。", tip:"「とりあえず版」のイメージ。provisional agenda＝仮の議題。", lv:3},
  {w:"exempt", m:"免除された", ex:"Nonprofit organizations are exempt from this tax.", exJa:"非営利団体はこの税を免除されている。", tip:"be exempt from 〜＝を免除されている。tax-exempt＝非課税。", lv:3},
  {w:"incur", m:"（費用・損失を）負う", ex:"You will incur additional charges for late payment.", exJa:"支払い遅延には追加料金が発生します。", tip:"incur costs / expenses＝費用が発生する。悪いものを「背負い込む」イメージ。", lv:3},
  {w:"waive", m:"（権利・料金を）放棄する、免除する", ex:"The bank waived the transfer fee.", exJa:"銀行は振込手数料を免除した。", tip:"waive a fee＝手数料を免除する。wave（手を振る）と同じ発音。「権利を手放す」。", lv:3},
  {w:"adjacent", m:"隣接した", ex:"The parking lot is adjacent to the building.", exJa:"駐車場は建物に隣接している。", tip:"adjacent to 〜＝に隣接した。next toのフォーマル版。地図・場所の説明で頻出。", lv:3},
  {w:"deteriorate", m:"悪化する", ex:"The building's condition has deteriorated.", exJa:"建物の状態は悪化した。", tip:"improveの反対。de（下へ）のイメージ。設備の老朽化の話で登場。", lv:3},
  {w:"plummet", m:"急落する", ex:"Sales plummeted last quarter.", exJa:"前四半期に売上が急落した。", tip:"鉛の重り（plumb）がまっすぐ落ちるイメージ。売上グラフの描写で頻出。", lv:3},
  {w:"surge", m:"急増する、急上昇", ex:"There was a surge in online orders.", exJa:"オンライン注文が急増した。", tip:"plummetの反対。a surge in 〜＝の急増。電源の「サージ」と同じ語。", lv:3},
  {w:"feasible", m:"実現可能な", ex:"The plan is technically feasible.", exJa:"その計画は技術的に実現可能だ。", tip:"feasibility study＝実現可能性調査。possibleより「実務的にできる」ニュアンス。", lv:3},
  {w:"expedite", m:"迅速に処理する、早める", ex:"We'll expedite your order.", exJa:"ご注文を急ぎで処理いたします。", tip:"ex（外へ）+ ped（足）→足かせを外す→早める。expedited shipping＝速達配送。", lv:3},
  {w:"redeem", m:"（クーポンを）引き換える", ex:"You can redeem this coupon at any store.", exJa:"このクーポンはどの店舗でもご利用いただけます。", tip:"redeem a coupon / voucher＝クーポンを商品と引き換える。ポイント交換の話でも頻出。", lv:3},
  {w:"solicit", m:"（意見・支援を）求める", ex:"We are soliciting feedback from customers.", exJa:"お客様からのご意見を募っております。", tip:"solicit feedback / donations＝意見・寄付を募る。アンケート依頼文で登場。", lv:3},
  {w:"stipulate", m:"（契約で）規定する", ex:"The contract stipulates that payment be made within 30 days.", exJa:"契約は30日以内の支払いを規定している。", tip:"契約書・規約に「明記する」こと。stipulation＝条項。", lv:3},
  {w:"delegate", m:"（権限を）委任する、代表者", ex:"The manager delegated the task to her assistant.", exJa:"部長はその業務をアシスタントに任せた。", tip:"動詞「委任する」名詞「代表者」。会議の話題ではdelegates＝出席代表者。", lv:3},
  {w:"consolidate", m:"統合する", ex:"The two branches will be consolidated.", exJa:"2つの支店は統合される。", tip:"con（共に）+ solid（固める）。部署統合・データ統合の文脈で登場。", lv:3},
  {w:"proficient", m:"熟達した、堪能な", ex:"Applicants must be proficient in Excel.", exJa:"応募者はExcelに堪能でなければならない。", tip:"be proficient in 〜＝に熟達している。求人の応募要件で頻出。proficiency＝習熟度。", lv:3},
  {w:"prospective", m:"見込みのある、将来の", ex:"We sent brochures to prospective clients.", exJa:"見込み客にパンフレットを送った。", tip:"prospective customer / employee＝見込み客・入社予定者。prospect＝見込み。", lv:3},
  {w:"adjourn", m:"（会議を）休会する", ex:"The meeting was adjourned until Thursday.", exJa:"会議は木曜日まで休会となった。", tip:"議事録（minutes）の締めの定番語。「散会する」。", lv:3},
  {w:"amend", m:"修正する、改正する", ex:"The contract was amended last month.", exJa:"契約書は先月修正された。", tip:"契約・法律を「改正する」。amendment＝修正条項。mend（直す）が入っている。", lv:3},
  {w:"liaison", m:"連絡（係）、連携", ex:"She acts as a liaison between the two departments.", exJa:"彼女は2部署間の連絡係を務めている。", tip:"読みは「リエゾン」。橋渡し役のこと。act as a liaisonの形で覚える。", lv:3},
  {w:"audit", m:"会計監査（する）", ex:"The accounts are audited every year.", exJa:"会計は毎年監査を受ける。", tip:"auditor＝監査人。audi（聞く）→帳簿の説明を聴く人が原義。", lv:3},
  {w:"patronage", m:"愛顧、ひいき", ex:"Thank you for your continued patronage.", exJa:"日頃のご愛顧ありがとうございます。", tip:"店の掲示や手紙の締めの決まり文句。patron＝常連客・後援者。", lv:3},
  {w:"courier", m:"宅配便（業者）", ex:"The documents were sent by courier.", exJa:"書類は宅配便で送られた。", tip:"by courier＝宅配便で。バイク便・国際宅配業者のこと。発音は「クーリア」。", lv:3},
];
