// TOEIC頻出単語データ
// w: 単語 / m: 意味 / ex: 例文 / exJa: 例文の和訳 / tip: 覚え方・用途 / lv: 1=基礎(〜600) 2=中級(〜730) 3=上級(860〜)
const WORDS = [
  // ===== レベル1: 基礎（〜600点） =====
  {w:"invoice", m:"請求書", ex:"Please pay the invoice by the end of the month.", exJa:"月末までに請求書のお支払いをお願いします。", tip:"billと違い企業間取引の請求書。Part 7の請求書文書で頻出。「送り状」の意味もある。", lv:1},
  {w:"appointment", m:"（面会の）約束、予約", ex:"I have an appointment with a client at three.", exJa:"3時に取引先と会う約束があります。", tip:"「アポ」の語源。病院の予約にも使う（席や部屋の予約はreservation）。", lv:1},
  {w:"schedule", m:"予定表、スケジュール", ex:"The meeting is scheduled for Monday.", exJa:"会議は月曜日に予定されています。", tip:"be scheduled for 〜「〜に予定されている」の形で頻出。ahead of schedule＝予定より早く。", lv:1},
  {w:"attend", m:"出席する", ex:"More than 100 people attended the conference.", exJa:"100人以上がその会議に出席した。", tip:"attend a meetingのように前置詞なしで使う。attendee＝出席者もセットで覚える。", lv:1},
  {w:"confirm", m:"確認する", ex:"I'm writing to confirm my reservation.", exJa:"予約の確認のためにご連絡しています。", tip:"ビジネスメールの定番動詞。confirmation number＝予約確認番号。", lv:1},
  {w:"deliver", m:"配達する", ex:"Your package will be delivered tomorrow.", exJa:"お荷物は明日配達されます。", tip:"名詞はdelivery（配達）。deliver a speech「スピーチを行う」の意味もPart 5で狙われる。", lv:1},
  {w:"employee", m:"従業員", ex:"All employees must wear ID badges.", exJa:"全従業員はIDバッジの着用が必要です。", tip:"employ（雇う）+ ee（〜される人）。employer（雇い主）との対比で覚える。", lv:1},
  {w:"customer", m:"顧客、（店の）客", ex:"The store offers discounts to regular customers.", exJa:"その店は常連客に割引を提供している。", tip:"custom（習慣）から「いつも来る人」。customer satisfaction＝顧客満足。", lv:1},
  {w:"order", m:"注文（する）", ex:"I'd like to place an order for ten chairs.", exJa:"椅子を10脚注文したいのですが。", tip:"place an order＝注文する。out of order＝故障中もPart 1・2で頻出。", lv:1},
  {w:"receipt", m:"領収書、レシート", ex:"Keep your receipt for a refund.", exJa:"返金には領収書を保管してください。", tip:"発音は「リシート」（pは読まない）。receive（受け取る）の名詞形。", lv:1},
  {w:"refund", m:"返金（する）", ex:"You can get a full refund within 30 days.", exJa:"30日以内なら全額返金が受けられます。", tip:"re（戻す）+ fund（資金）。full refund＝全額返金の形で頻出。", lv:1},
  {w:"available", m:"利用可能な、都合がつく", ex:"Is the manager available now?", exJa:"部長は今、手が空いていますか？", tip:"人にも物にも使える万能語。「入手できる・空いている・都合がつく」は全部これ。", lv:1},
  {w:"purchase", m:"購入する、購入品", ex:"Thank you for your recent purchase.", exJa:"この度はお買い上げありがとうございます。", tip:"buyのフォーマル版。名詞でも動詞でも使う。proof of purchase＝購入証明。", lv:1},
  {w:"provide", m:"提供する", ex:"We provide free shipping on all orders.", exJa:"全てのご注文で送料無料をご提供します。", tip:"provide A with B＝AにBを提供する。語法問題の定番。", lv:1},
  {w:"offer", m:"申し出る、（条件を）提示する", ex:"They offered me the position.", exJa:"彼らは私にその職を打診してくれた。", tip:"名詞では「割引・提案」。job offer＝採用通知、special offer＝特別セール。", lv:1},
  {w:"contract", m:"契約（書）", ex:"Both parties signed the contract.", exJa:"両者が契約書に署名した。", tip:"sign a contract＝契約を結ぶ。con（共に）+ tract（引く）→互いに取り決める。", lv:1},
  {w:"department", m:"部署、部門", ex:"She works in the sales department.", exJa:"彼女は営業部で働いている。", tip:"〜departmentで部署名になる。department store＝百貨店（部門ごとの店）。", lv:1},
  {w:"manager", m:"部長、責任者", ex:"Please contact the store manager.", exJa:"店長にご連絡ください。", tip:"TOEICでは「部長・店長・責任者」。hiring manager＝採用担当者。", lv:1},
  {w:"product", m:"製品", ex:"This product comes with a two-year warranty.", exJa:"この製品には2年保証が付いています。", tip:"produce（生産する）の名詞。productive＝生産的な、も併せて覚える。", lv:1},
  {w:"announce", m:"公表する、発表する", ex:"The company announced a new product line.", exJa:"その会社は新製品ラインを発表した。", tip:"announcement＝お知らせは、Part 4のアナウンス問題の定番語。", lv:1},
  {w:"apply", m:"申し込む、応募する", ex:"She applied for the marketing position.", exJa:"彼女はマーケティング職に応募した。", tip:"apply for 〜＝に応募する。applicant＝応募者、application＝応募（書類）。", lv:1},
  {w:"hire", m:"雇う", ex:"We're hiring additional staff for the summer.", exJa:"夏に向けて追加スタッフを雇っています。", tip:"new hire＝新入社員という名詞用法もある。英国では「（車などを）借りる」の意味も。", lv:1},
  {w:"salary", m:"給料", ex:"The job offers a competitive salary.", exJa:"その仕事は他社に負けない給料を提示している。", tip:"月給・年俸のイメージ（時給はwage）。competitive salaryは求人広告の決まり文句。", lv:1},
  {w:"warranty", m:"（品質）保証、保証書", ex:"The warranty covers parts and labor.", exJa:"保証は部品代と作業代をカバーします。", tip:"under warranty＝保証期間内。guaranteeとほぼ同義だが、書類はwarranty。", lv:1},
  {w:"shipment", m:"発送、出荷（品）", ex:"The shipment will arrive on Friday.", exJa:"発送品は金曜日に到着予定です。", tip:"ship＝発送する（船以外でも使う）。shipping＝送料・発送。", lv:1},
  {w:"supply", m:"供給、備品", ex:"Office supplies are stored in the cabinet.", exJa:"事務用品はキャビネットに保管されています。", tip:"office supplies＝事務用品は超頻出。supplier＝納入業者。", lv:1},
  {w:"repair", m:"修理する", ex:"The copier needs to be repaired.", exJa:"コピー機は修理が必要です。", tip:"Part 1で「修理中の人」の描写に頻出。fixよりフォーマル。", lv:1},
  {w:"install", m:"設置する、インストールする", ex:"New software will be installed on all computers.", exJa:"全てのPCに新しいソフトがインストールされます。", tip:"機械・設備の「設置」にも使う。installation＝設置（工事）。", lv:1},
  {w:"submit", m:"提出する", ex:"Please submit your report by Friday.", exJa:"金曜日までに報告書を提出してください。", tip:"sub（下に）+ mit（送る）→差し出す。submit A to Bの形で頻出。", lv:1},
  {w:"complete", m:"完了する、（書類に）記入する", ex:"Please complete this form.", exJa:"この用紙にご記入ください。", tip:"「完了する」だけでなく「記入する」（＝fill out）の意味がTOEICでは重要。", lv:1},
  {w:"colleague", m:"同僚", ex:"I discussed the plan with my colleagues.", exJa:"同僚たちとその計画について話し合った。", tip:"co（共に）+ league（仲間）。coworkerと同義。アクセントは前（カ）にある。", lv:1},
  {w:"client", m:"取引先、依頼人", ex:"The lawyer met with a client.", exJa:"その弁護士は依頼人と面会した。", tip:"弁護士・コンサルなど専門サービスの顧客。小売店の客はcustomer。", lv:1},

  // ===== レベル2: 中級（〜730点） =====
  {w:"accommodate", m:"収容する、（要望に）応える", ex:"The hall can accommodate 300 guests.", exJa:"そのホールは300人の客を収容できます。", tip:"「収容する」と「（要望に）応える」の2つの意味。accommodations＝宿泊施設。", lv:2},
  {w:"itinerary", m:"旅程（表）", ex:"I'll send you the itinerary for your business trip.", exJa:"出張の旅程表をお送りします。", tip:"出張・旅行関連の文書で定番。読み方は「アイティネラリー」。", lv:2},
  {w:"reimburse", m:"（経費を）払い戻す", ex:"Employees will be reimbursed for travel expenses.", exJa:"従業員は出張費の払い戻しを受けられます。", tip:"経費精算の話題で頻出。re（戻す）+ burse（財布）。reimbursement＝払い戻し。", lv:2},
  {w:"expire", m:"期限が切れる", ex:"My passport expires next month.", exJa:"パスポートは来月期限が切れます。", tip:"expiration date＝有効期限。クーポンや契約の話題で頻出。", lv:2},
  {w:"negotiate", m:"交渉する", ex:"We negotiated a better price with the supplier.", exJa:"納入業者ともっと良い価格を交渉した。", tip:"日本語の「ネゴ」の語源。negotiation＝交渉。", lv:2},
  {w:"postpone", m:"延期する", ex:"The event was postponed due to rain.", exJa:"イベントは雨のため延期された。", tip:"post（後に）+ pone（置く）。put offと同義。Part 2の応答で頻出。", lv:2},
  {w:"inquiry", m:"問い合わせ", ex:"Thank you for your inquiry about our services.", exJa:"弊社サービスへのお問い合わせありがとうございます。", tip:"inquire＝問い合わせる。ビジネスメールの冒頭の定番フレーズ。", lv:2},
  {w:"estimate", m:"見積もり、見積もる", ex:"Could you give me an estimate for the repairs?", exJa:"修理の見積もりをいただけますか？", tip:"名詞「見積もり」と動詞「見積もる」の両方で使う。estimated time of arrival＝到着予定時刻。", lv:2},
  {w:"merchandise", m:"商品", ex:"All merchandise is 20% off this week.", exJa:"今週は全商品20％引きです。", tip:"集合名詞で数えられない。merchant（商人）の関連語。goodsと同義。", lv:2},
  {w:"inventory", m:"在庫、棚卸し", ex:"We're taking inventory this weekend.", exJa:"今週末に棚卸しをします。", tip:"take inventory＝棚卸しをする。在庫はstockとも言う。", lv:2},
  {w:"facility", m:"施設、設備", ex:"The hotel has excellent fitness facilities.", exJa:"そのホテルには素晴らしいフィットネス施設があります。", tip:"複数形facilitiesでよく使う。「設備・施設」を表す万能語。", lv:2},
  {w:"agenda", m:"議題、協議事項", ex:"The first item on the agenda is the budget.", exJa:"議題の最初の項目は予算です。", tip:"item on the agenda＝議題の項目。会議文書（Part 7）の定番。", lv:2},
  {w:"quarterly", m:"四半期の", ex:"The quarterly report is due next week.", exJa:"四半期報告書の期限は来週です。", tip:"quarter＝4分の1→3か月。annually（年1回）、monthly（月1回）とセットで覚える。", lv:2},
  {w:"revenue", m:"収益、歳入", ex:"The company's revenue increased by 15%.", exJa:"会社の収益は15％増加した。", tip:"売上高・総収入のこと。profit（利益）との違いに注意。増減の話題で頻出。", lv:2},
  {w:"budget", m:"予算", ex:"We need to stay within the budget.", exJa:"予算内に収める必要があります。", tip:"within the budget＝予算内で。budget cut＝予算削減。", lv:2},
  {w:"extend", m:"延長する", ex:"They extended the deadline by one week.", exJa:"締め切りが1週間延長された。", tip:"ex（外へ）+ tend（伸ばす）。extension＝延長・内線番号。", lv:2},
  {w:"renovate", m:"改装する", ex:"The office is being renovated.", exJa:"オフィスは改装中です。", tip:"re（再び）+ nov（新しく）。renovation＝改装工事はPart 3・4の頻出テーマ。", lv:2},
  {w:"recruit", m:"（人材を）募集する", ex:"The company is recruiting engineers.", exJa:"その会社はエンジニアを募集している。", tip:"日本語の「リクルート」そのまま。recruiter＝採用担当者。", lv:2},
  {w:"retire", m:"退職する、引退する", ex:"He retired after 30 years with the company.", exJa:"彼は30年勤めた会社を退職した。", tip:"retirement party＝退職記念パーティーはTOEIC頻出イベント。", lv:2},
  {w:"promote", m:"昇進させる、販売促進する", ex:"She was promoted to sales manager.", exJa:"彼女は営業部長に昇進した。", tip:"「昇進させる」と「販促する」の2つ。promotion＝昇進・販促キャンペーン。", lv:2},
  {w:"transfer", m:"異動させる、移す", ex:"He was transferred to the Osaka branch.", exJa:"彼は大阪支店に異動になった。", tip:"電話の「おつなぎします」（transfer your call）や乗り換えにも使う。", lv:2},
  {w:"evaluate", m:"評価する", ex:"Managers evaluate employee performance annually.", exJa:"管理職は毎年従業員の業績を評価する。", tip:"e + valu（価値）+ ate→価値を測る。performance evaluation＝人事評価。", lv:2},
  {w:"implement", m:"実施する、導入する", ex:"The new policy will be implemented in April.", exJa:"新しい方針は4月に実施される。", tip:"計画・制度を「実行に移す」こと。implementation＝実施。", lv:2},
  {w:"launch", m:"（新商品を）発売する、開始する", ex:"The company will launch a new smartphone.", exJa:"その会社は新しいスマートフォンを発売する。", tip:"ロケットの「打ち上げ」から新商品の「発売」へ。product launch＝新商品発売。", lv:2},
  {w:"expand", m:"拡大する", ex:"The firm plans to expand into Asia.", exJa:"その会社はアジアへの進出を計画している。", tip:"expansion＝拡大。expend（費やす）とのスペル違いに注意。", lv:2},
  {w:"distribute", m:"配布する、流通させる", ex:"Handouts will be distributed before the seminar.", exJa:"資料はセミナーの前に配布されます。", tip:"dis（別々に）+ tribute（与える）。distributor＝販売代理店。", lv:2},
  {w:"manufacture", m:"製造する", ex:"The parts are manufactured in Vietnam.", exJa:"その部品はベトナムで製造されている。", tip:"manu（手）+ fact（作る）。manufacturer＝メーカー・製造業者は超頻出。", lv:2},
  {w:"subscribe", m:"定期購読する", ex:"Subscribe to our newsletter for updates.", exJa:"最新情報はニュースレターをご購読ください。", tip:"subscribe to 〜の形で使う。subscription＝定期購読（サブスク）。", lv:2},
  {w:"attach", m:"添付する", ex:"I've attached the file to this email.", exJa:"このメールにファイルを添付しました。", tip:"attached file＝添付ファイル。メール問題の定番。反意語はdetach。", lv:2},
  {w:"notify", m:"通知する", ex:"We will notify you of the results by email.", exJa:"結果はメールでお知らせします。", tip:"notify A of B＝AにBを知らせる。notification＝通知。", lv:2},
  {w:"comply", m:"（規則に）従う", ex:"All buildings must comply with safety regulations.", exJa:"全ての建物は安全基準に従わなければならない。", tip:"comply with 〜＝に従う。compliance＝法令遵守（コンプラ）。", lv:2},
  {w:"feature", m:"特徴、目玉にする", ex:"The new model features a larger screen.", exJa:"新モデルはより大きな画面が特徴です。", tip:"動詞「〜を特徴とする・目玉にする」が重要。featured product＝注目商品。", lv:2},

  // ===== レベル3: 上級（860点〜） =====
  {w:"lucrative", m:"儲かる、利益の大きい", ex:"They signed a lucrative contract.", exJa:"彼らは利益の大きい契約を結んだ。", tip:"profitableの上位語彙。lucrative deal / marketなどお金の話題で登場。", lv:3},
  {w:"meticulous", m:"細心の、几帳面な", ex:"She is meticulous about details.", exJa:"彼女は細部まで非常に几帳面だ。", tip:"求人や人物評価で登場。attention to detail（細部への注意）とセットで覚える。", lv:3},
  {w:"endorse", m:"支持する、推奨する", ex:"The product is endorsed by famous athletes.", exJa:"その製品は有名アスリートに推奨されている。", tip:"有名人による「推薦・宣伝」や案の「支持」。小切手の裏書きが原義。", lv:3},
  {w:"procurement", m:"調達", ex:"He works in the procurement department.", exJa:"彼は調達部門で働いている。", tip:"procure＝調達する。purchasing（購買）のフォーマル版。", lv:3},
  {w:"remuneration", m:"報酬", ex:"The position offers generous remuneration.", exJa:"その職は高額の報酬を提示している。", tip:"給与・報酬のフォーマル語。求人広告（Part 7）で登場。", lv:3},
  {w:"discrepancy", m:"不一致、食い違い", ex:"There is a discrepancy between the two reports.", exJa:"2つの報告書の間に食い違いがある。", tip:"請求額や在庫数の「不一致」はTOEICの定番トラブル。", lv:3},
  {w:"contingency", m:"不測の事態", ex:"We need a contingency plan.", exJa:"不測の事態への対応策が必要だ。", tip:"contingency plan＝緊急時対応計画、の形で覚える。", lv:3},
  {w:"streamline", m:"合理化する、効率化する", ex:"The company streamlined its ordering process.", exJa:"会社は注文プロセスを効率化した。", tip:"stream（流れ）+ line→流線形に→無駄をなくす。業務改善の話題で頻出。", lv:3},
  {w:"unprecedented", m:"前例のない", ex:"The store saw unprecedented demand.", exJa:"その店はかつてない需要に見舞われた。", tip:"un + precedent（前例）+ ed。「前例のない成長・需要」などプラスの文脈が多い。", lv:3},
  {w:"provisional", m:"暫定的な", ex:"A provisional schedule will be sent this week.", exJa:"暫定スケジュールが今週送られます。", tip:"「とりあえず版」のイメージ。provisional agenda＝仮の議題。", lv:3},
  {w:"exempt", m:"免除された", ex:"Nonprofit organizations are exempt from this tax.", exJa:"非営利団体はこの税を免除されている。", tip:"be exempt from 〜＝を免除されている。tax-exempt＝非課税。", lv:3},
  {w:"incur", m:"（費用・損失を）負う", ex:"You will incur additional charges for late payment.", exJa:"支払い遅延には追加料金が発生します。", tip:"incur costs / expenses＝費用が発生する。悪いものを「背負い込む」イメージ。", lv:3},
  {w:"waive", m:"（権利・料金を）放棄する、免除する", ex:"The bank waived the transfer fee.", exJa:"銀行は振込手数料を免除した。", tip:"waive a fee＝手数料を免除する。wave（手を振る）と同じ発音。「権利を手放す」。", lv:3},
  {w:"adjacent", m:"隣接した", ex:"The parking lot is adjacent to the building.", exJa:"駐車場は建物に隣接している。", tip:"adjacent to 〜＝に隣接した。next toのフォーマル版。地図・場所の説明で頻出。", lv:3},
  {w:"deteriorate", m:"悪化する", ex:"The building's condition has deteriorated.", exJa:"建物の状態は悪化した。", tip:"improveの反対。de（下へ）のイメージ。設備の老朽化の話で登場。", lv:3},
  {w:"plummet", m:"急落する", ex:"Sales plummeted last quarter.", exJa:"前四半期に売上が急落した。", tip:"鉛の重り（plumb）がまっすぐ落ちるイメージ。売上グラフの描写で頻出。", lv:3},
  {w:"surge", m:"急増する、急上昇", ex:"There was a surge in online orders.", exJa:"オンライン注文が急増した。", tip:"plummetの反対。a surge in 〜＝の急増。電源の「サージ」と同じ語。", lv:3},
  {w:"feasible", m:"実現可能な", ex:"The plan is technically feasible.", exJa:"その計画は技術的に実現可能だ。", tip:"feasibility study＝実現可能性調査。possibleより「実務的にできる」ニュアンス。", lv:3},
  {w:"expedite", m:"迅速に処理する、早める", ex:"We'll expedite your order.", exJa:"ご注文を急ぎで処理いたします。", tip:"ex（外へ）+ ped（足）→足かせを外す→早める。expedited shipping＝速達配送。", lv:3},
  {w:"redeem", m:"（クーポンを）引き換える", ex:"You can redeem this coupon at any store.", exJa:"このクーポンはどの店舗でもご利用いただけます。", tip:"redeem a coupon / voucher＝クーポンを商品と引き換える。ポイント交換の話でも頻出。", lv:3},
  {w:"solicit", m:"（意見・支援を）求める", ex:"We are soliciting feedback from customers.", exJa:"お客様からのご意見を募っております。", tip:"solicit feedback / donations＝意見・寄付を募る。アンケート依頼文で登場。", lv:3},
  {w:"stipulate", m:"（契約で）規定する", ex:"The contract stipulates that payment be made within 30 days.", exJa:"契約は30日以内の支払いを規定している。", tip:"契約書・規約に「明記する」こと。stipulation＝条項。", lv:3},
  {w:"delegate", m:"（権限を）委任する、代表者", ex:"The manager delegated the task to her assistant.", exJa:"部長はその業務をアシスタントに任せた。", tip:"動詞「委任する」名詞「代表者」。会議の話題ではdelegates＝出席代表者。", lv:3},
  {w:"consolidate", m:"統合する", ex:"The two branches will be consolidated.", exJa:"2つの支店は統合される。", tip:"con（共に）+ solid（固める）。部署統合・データ統合の文脈で登場。", lv:3},
  {w:"proficient", m:"熟達した、堪能な", ex:"Applicants must be proficient in Excel.", exJa:"応募者はExcelに堪能でなければならない。", tip:"be proficient in 〜＝に熟達している。求人の応募要件で頻出。proficiency＝習熟度。", lv:3},
  {w:"prospective", m:"見込みのある、将来の", ex:"We sent brochures to prospective clients.", exJa:"見込み客にパンフレットを送った。", tip:"prospective customer / employee＝見込み客・入社予定者。prospect＝見込み。", lv:3},
  {w:"adjourn", m:"（会議を）休会する", ex:"The meeting was adjourned until Thursday.", exJa:"会議は木曜日まで休会となった。", tip:"議事録（minutes）の締めの定番語。「散会する」。", lv:3},
  {w:"amend", m:"修正する、改正する", ex:"The contract was amended last month.", exJa:"契約書は先月修正された。", tip:"契約・法律を「改正する」。amendment＝修正条項。mend（直す）が入っている。", lv:3},
  {w:"liaison", m:"連絡（係）、連携", ex:"She acts as a liaison between the two departments.", exJa:"彼女は2部署間の連絡係を務めている。", tip:"読みは「リエゾン」。橋渡し役のこと。act as a liaisonの形で覚える。", lv:3},
  {w:"audit", m:"会計監査（する）", ex:"The accounts are audited every year.", exJa:"会計は毎年監査を受ける。", tip:"auditor＝監査人。audi（聞く）→帳簿の説明を聴く人が原義。", lv:3},
  {w:"patronage", m:"愛顧、ひいき", ex:"Thank you for your continued patronage.", exJa:"日頃のご愛顧ありがとうございます。", tip:"店の掲示や手紙の締めの決まり文句。patron＝常連客・後援者。", lv:3},
  {w:"courier", m:"宅配便（業者）", ex:"The documents were sent by courier.", exJa:"書類は宅配便で送られた。", tip:"by courier＝宅配便で。バイク便・国際宅配業者のこと。発音は「クーリア」。", lv:3},

  // ===== 追加分（レベル1: 基礎） =====
  {w:"reserve", m:"（席・部屋を）予約する", ex:"I'd like to reserve a table for six o'clock.", exJa:"6時にテーブルを予約したいのですが。", tip:"レストラン・ホテルの予約はreserve／reservation。人と会う約束はappointment。", lv:1},
  {w:"document", m:"書類", ex:"Please review the attached documents before the meeting.", exJa:"会議の前に添付書類をご確認ください。", tip:"動詞では「記録する」。documentation＝文書一式。", lv:1},
  {w:"equipment", m:"機器、装置", ex:"Safety equipment must be worn at all times.", exJa:"安全装備は常に着用しなければならない。", tip:"不可算名詞（×equipments）。be equipped with 〜＝を備えている。", lv:1},
  {w:"branch", m:"支店", ex:"She was transferred to the New York branch.", exJa:"彼女はニューヨーク支店に異動になった。", tip:"本来は「枝」。会社の枝＝支店・支社。branch officeとも言う。", lv:1},
  {w:"headquarters", m:"本社", ex:"The company moved its headquarters to Osaka.", exJa:"その会社は本社を大阪に移転した。", tip:"常に複数形のsが付く。略はHQ。⇔branch（支店）。", lv:1},
  {w:"warehouse", m:"倉庫", ex:"The goods are stored in the warehouse.", exJa:"商品は倉庫に保管されている。", tip:"ware（商品）+ house（家）。Part 1の倉庫作業の写真でも頻出。", lv:1},
  {w:"passenger", m:"乗客", ex:"Passengers should proceed to Gate 12.", exJa:"乗客の皆様は12番ゲートへお進みください。", tip:"空港・駅のアナウンス（Part 4）の定番語。", lv:1},
  {w:"luggage", m:"手荷物", ex:"You can leave your luggage at the front desk.", exJa:"お荷物はフロントにお預けいただけます。", tip:"不可算名詞。米語ではbaggageも同義。a piece of luggageと数える。", lv:1},
  {w:"fare", m:"（乗り物の）運賃", ex:"The bus fare will increase next month.", exJa:"バス運賃は来月値上げされる。", tip:"乗り物の運賃専用。fair（公平な・見本市）と同音なので注意。", lv:1},
  {w:"fee", m:"手数料、（サービスの）料金", ex:"There is a small fee for parking.", exJa:"駐車には少額の料金がかかります。", tip:"entrance fee＝入場料、late fee＝延滞料。専門サービスへの支払いに使う。", lv:1},
  {w:"conference", m:"大会議、協議会", ex:"She is attending a conference in Boston.", exJa:"彼女はボストンでの会議に出席している。", tip:"meetingより大規模で公式。conference room＝会議室。", lv:1},
  {w:"reschedule", m:"予定を変更する", ex:"Can we reschedule the meeting for Friday?", exJa:"会議を金曜日に変更できますか？", tip:"re（再び）+ schedule。Part 2・3の「予定変更」の話題の中心語。", lv:1},
  {w:"delay", m:"遅らせる、遅延", ex:"The flight was delayed due to heavy snow.", exJa:"便は大雪のため遅れた。", tip:"be delayed＝遅れる。without delay＝遅滞なく。交通トラブルの定番語。", lv:1},
  {w:"depart", m:"出発する", ex:"The train departs from Platform 3.", exJa:"列車は3番ホームから出発します。", tip:"departure＝出発（⇔arrival）。departure time＝出発時刻。", lv:1},
  {w:"destination", m:"目的地", ex:"The package arrived at its destination on time.", exJa:"荷物は時間通りに目的地に到着した。", tip:"配送・旅行の話題で頻出。tourist destination＝観光地。", lv:1},
  {w:"payment", m:"支払い", ex:"Payment can be made by credit card.", exJa:"お支払いはクレジットカードで可能です。", tip:"make a payment＝支払う。payment method＝支払い方法。", lv:1},
  {w:"deposit", m:"頭金、預け入れ", ex:"A deposit of 10% is required to confirm your booking.", exJa:"予約確定には10％の頭金が必要です。", tip:"「頭金・保証金」と「預け入れる」。銀行・ホテル・賃貸の話題で登場。", lv:1},
  {w:"discount", m:"割引", ex:"Members receive a 15% discount.", exJa:"会員は15％の割引を受けられます。", tip:"at a discount＝割引価格で。discounted price＝割引価格。", lv:1},
  {w:"brochure", m:"パンフレット", ex:"Please pick up a brochure at the entrance.", exJa:"入口でパンフレットをお取りください。", tip:"旅行・商品案内の冊子。発音は「ブロウシュア」。", lv:1},
  {w:"instruction", m:"説明書、指示", ex:"Follow the instructions on the package.", exJa:"パッケージの説明書きに従ってください。", tip:"instructionsと複数形で「説明書」。instructor＝講師。", lv:1},
  {w:"resume", m:"履歴書", ex:"Please send your resume and cover letter.", exJa:"履歴書とカバーレターをお送りください。", tip:"名詞（レジュメイ）は履歴書、動詞（リジューム）は「再開する」。アクセントが変わる。", lv:1},
  {w:"interview", m:"面接", ex:"She has a job interview on Thursday.", exJa:"彼女は木曜日に就職面接がある。", tip:"interviewer＝面接官、interviewee＝面接を受ける人。", lv:1},
  {w:"candidate", m:"候補者", ex:"We interviewed five candidates for the position.", exJa:"その職に5人の候補者を面接した。", tip:"選挙の候補者にも使う。successful candidate＝採用者・合格者。", lv:1},
  {w:"workshop", m:"研修会、講習会", ex:"The company offers workshops on presentation skills.", exJa:"会社はプレゼンスキルの研修会を開いている。", tip:"参加型の講習会。工場の「作業場」の意味もある。", lv:1},
  {w:"deadline", m:"締め切り", ex:"The deadline for applications is March 31.", exJa:"応募の締め切りは3月31日です。", tip:"meet the deadline＝間に合う、miss the deadline＝遅れる。", lv:1},
  {w:"signature", m:"署名", ex:"We need your signature on this form.", exJa:"この用紙にご署名が必要です。", tip:"sign（署名する）の名詞。有名人の「サイン」はautograph。", lv:1},
  {w:"account", m:"口座", ex:"I'd like to open a bank account.", exJa:"銀行口座を開設したいのですが。", tip:"「口座」のほか「取引先」「説明」の意味も。accounting＝経理。", lv:1},
  {w:"suggest", m:"提案する", ex:"I suggest taking an earlier train.", exJa:"もっと早い電車に乗ることを提案します。", tip:"suggest -ingの形が語法問題で頻出（to不定詞は不可）。suggestion＝提案。", lv:1},
  {w:"accept", m:"受け入れる、応じる", ex:"We accept all major credit cards.", exJa:"主要なクレジットカードを全てご利用いただけます。", tip:"except（〜を除いて）とスペル混同に注意。acceptance＝受諾。", lv:1},
  {w:"exchange", m:"交換する", ex:"Can I exchange this shirt for a larger size?", exJa:"このシャツを大きいサイズに交換できますか？", tip:"exchange A for B＝AをBと交換する。返品・両替の話題で頻出。", lv:1},
  {w:"regular", m:"定期的な、いつもの", ex:"Regular maintenance keeps the machine running well.", exJa:"定期的な保守が機械の調子を保つ。", tip:"regular customer＝常連客、regular hours＝通常営業時間。", lv:1},
  {w:"sign", m:"看板、標識", ex:"The sign says the store opens at ten.", exJa:"看板には10時開店と書いてある。", tip:"名詞「看板・標識」がPart 1で頻出。動詞は「署名する」。", lv:1},
  {w:"crowded", m:"混雑した", ex:"The restaurant is always crowded at noon.", exJa:"そのレストランは正午はいつも混んでいる。", tip:"crowd（群衆）+ ed。be crowded with 〜＝で混雑している。", lv:1},
  {w:"nearby", m:"近くの、近くに", ex:"Is there a pharmacy nearby?", exJa:"近くに薬局はありますか？", tip:"形容詞（a nearby hotel）にも副詞にも使える。", lv:1},
  {w:"request", m:"依頼（する）、要請", ex:"You can request a refund online.", exJa:"返金はオンラインで依頼できます。", tip:"request that 〜の文では動詞が原形になる点（仮定法現在）が狙われる。", lv:1},

  // ===== 追加分（レベル2: 中級） =====
  {w:"decline", m:"辞退する、減少する", ex:"He declined the invitation to the banquet.", exJa:"彼は宴会への招待を辞退した。", tip:"丁寧に断るニュアンス。「減少する」の意味もグラフ問題で頻出。", lv:2},
  {w:"participate", m:"参加する", ex:"More than 50 companies participated in the trade show.", exJa:"50社以上が見本市に参加した。", tip:"participate in 〜＝に参加する。participant＝参加者。", lv:2},
  {w:"register", m:"登録する", ex:"Please register for the seminar by Friday.", exJa:"金曜日までにセミナーへの登録をお願いします。", tip:"register for 〜＝に登録する。registration＝登録。cash register＝レジ。", lv:2},
  {w:"permit", m:"許可証", ex:"You need a permit to park here.", exJa:"ここに駐車するには許可証が必要です。", tip:"名詞（パーミット）は許可証、動詞（パミット）は許可する。parking permit＝駐車許可証。", lv:2},
  {w:"approve", m:"承認する", ex:"The board approved the new budget.", exJa:"取締役会は新予算を承認した。", tip:"approve of 〜＝に賛成する。approval＝承認。⇔reject（却下する）。", lv:2},
  {w:"applicant", m:"応募者", ex:"Applicants must have three years of experience.", exJa:"応募者は3年の経験が必要です。", tip:"apply（応募する）+ ant（人）。求人広告（Part 7）の定番。", lv:2},
  {w:"venue", m:"開催地、会場", ex:"The venue for the conference has been changed.", exJa:"会議の会場が変更になった。", tip:"イベント・式典の開催場所。event venue＝イベント会場。", lv:2},
  {w:"audience", m:"聴衆、観客", ex:"The audience applauded after the speech.", exJa:"聴衆はスピーチの後に拍手した。", tip:"集合名詞。講演・コンサートの「聴衆」。テレビの視聴者にも使う。", lv:2},
  {w:"exhibit", m:"展示する、展示品", ex:"Her paintings are exhibited at the gallery.", exJa:"彼女の絵画はギャラリーに展示されている。", tip:"exhibition＝展覧会。美術館・見本市の話題で頻出。", lv:2},
  {w:"admission", m:"入場（料）", ex:"Admission to the museum is free on Mondays.", exJa:"月曜は美術館の入場が無料です。", tip:"admission fee＝入場料。admit＝入場を認める。", lv:2},
  {w:"refreshments", m:"軽食、飲み物", ex:"Refreshments will be served after the presentation.", exJa:"プレゼンの後に軽食が提供されます。", tip:"複数形で「軽食・飲み物」。イベント案内文の決まり文句。", lv:2},
  {w:"banquet", m:"宴会、晩餐会", ex:"The awards banquet will be held at the hotel.", exJa:"授賞式の宴会はホテルで開かれます。", tip:"公式な晩餐会・祝宴。banquet hall＝宴会場。", lv:2},
  {w:"anniversary", m:"記念日、〜周年", ex:"The store is celebrating its 20th anniversary.", exJa:"その店は20周年を祝っている。", tip:"anni（年）+ vers（回る）。記念セールの文脈で頻出。", lv:2},
  {w:"ceremony", m:"式典", ex:"The opening ceremony starts at nine.", exJa:"開会式は9時に始まります。", tip:"awards ceremony＝授賞式、opening ceremony＝開会式・開店式。", lv:2},
  {w:"appliance", m:"家電製品", ex:"This store sells kitchen appliances.", exJa:"この店は台所用家電を販売している。", tip:"home appliances＝家電製品。applyとは意味が違うので注意。", lv:2},
  {w:"utility", m:"公共料金", ex:"Utilities are included in the rent.", exJa:"公共料金は家賃に含まれています。", tip:"複数形utilitiesで「電気・ガス・水道料金」。賃貸の話題で頻出。", lv:2},
  {w:"lease", m:"賃貸借契約", ex:"They signed a two-year lease on the office.", exJa:"彼らはオフィスの2年の賃貸借契約を結んだ。", tip:"sign a lease＝賃貸契約を結ぶ。「リース契約」の語源。", lv:2},
  {w:"tenant", m:"賃借人、テナント", ex:"Tenants must give 30 days notice before moving out.", exJa:"賃借人は退去の30日前に通知が必要です。", tip:"ビル・アパートの「入居者」。⇔landlord（大家）。", lv:2},
  {w:"landlord", m:"大家、家主", ex:"The landlord agreed to repair the heater.", exJa:"大家は暖房の修理に同意した。", tip:"land（土地）+ lord（主）。賃貸トラブルの話題（Part 3・7）で登場。", lv:2},
  {w:"real estate", m:"不動産", ex:"She works for a real estate agency.", exJa:"彼女は不動産会社で働いている。", tip:"real estate agent＝不動産業者。物件・引っ越しの話題で頻出。", lv:2},
  {w:"commute", m:"通勤する", ex:"He commutes to work by train.", exJa:"彼は電車で通勤している。", tip:"commuter＝通勤者。commuting time＝通勤時間。", lv:2},
  {w:"pedestrian", m:"歩行者", ex:"This street is for pedestrians only.", exJa:"この通りは歩行者専用です。", tip:"ped（足）が語源。pedestrian crossing＝横断歩道。Part 1でも登場。", lv:2},
  {w:"vehicle", m:"車両、乗り物", ex:"Parking is available for 100 vehicles.", exJa:"100台分の駐車場があります。", tip:"車・トラック・バスの総称。発音は「ヴィーイクル」（hは読まない）。", lv:2},
  {w:"detour", m:"迂回（路）", ex:"Drivers should take a detour due to road construction.", exJa:"道路工事のため迂回してください。", tip:"de（離れて）+ tour（回る）。工事・渋滞のアナウンスで頻出。", lv:2},
  {w:"construction", m:"建設（工事）", ex:"A new bridge is under construction.", exJa:"新しい橋が建設中だ。", tip:"under construction＝建設中・工事中はPart 1の頻出表現。", lv:2},
  {w:"maintenance", m:"保守点検、整備", ex:"The elevator is closed for maintenance.", exJa:"エレベーターは保守点検のため停止中です。", tip:"maintain（維持する）の名詞。設備点検のお知らせ文で頻出。", lv:2},
  {w:"currently", m:"現在は", ex:"We are currently hiring part-time staff.", exJa:"現在アルバイトを募集中です。", tip:"current（現在の）+ ly。現在（進行）形とセットで使う。", lv:2},
  {w:"approximately", m:"およそ、約", ex:"The flight takes approximately two hours.", exJa:"フライトは約2時間かかります。", tip:"aboutのフォーマル版。approx.と略される。数字を問う設問のキーワード。", lv:2},
  {w:"frequently", m:"頻繁に", ex:"This question is frequently asked.", exJa:"この質問はよく尋ねられる。", tip:"FAQ（frequently asked questions）のF。frequent＝頻繁な。", lv:2},
  {w:"immediately", m:"直ちに、すぐに", ex:"Please contact us immediately if there is a problem.", exJa:"問題があればすぐにご連絡ください。", tip:"at once／right awayと同義。immediate supervisor＝直属の上司も頻出。", lv:2},
  {w:"via", m:"〜経由で、〜によって", ex:"Send the file via email.", exJa:"ファイルをメールで送ってください。", tip:"via Chicago＝シカゴ経由。前置詞問題（Part 5）で登場。", lv:2},
  {w:"due to", m:"〜が原因で", ex:"The event was canceled due to bad weather.", exJa:"イベントは悪天候のため中止された。", tip:"because ofと同義の前置詞句。dueだけなら「期限の」。", lv:2},
  {w:"voucher", m:"商品引換券、利用券", ex:"This voucher is valid for six months.", exJa:"この商品引換券は6か月間有効です。", tip:"gift voucher＝商品券。redeem a voucher＝引き換える、とセットで覚える。", lv:2},
  {w:"out of stock", m:"在庫切れの", ex:"That item is currently out of stock.", exJa:"その商品は現在在庫切れです。", tip:"⇔in stock（在庫あり）。買い物・注文の会話（Part 3）で頻出。", lv:2},
  {w:"complimentary", m:"無料の、サービスの", ex:"Guests receive a complimentary breakfast.", exJa:"宿泊客は無料の朝食が付きます。", tip:"free of chargeと同義。complement（補完する）と混同注意。ホテル・機内で頻出。", lv:2},

  // ===== 追加分（レベル3: 上級） =====
  {w:"itemize", m:"項目別に記載する", ex:"Please submit an itemized list of expenses.", exJa:"経費の明細リストを提出してください。", tip:"item（項目）+ ize。itemized bill＝明細付き請求書。経費精算の文脈で登場。", lv:3},
  {w:"allocate", m:"（資金などを）割り当てる", ex:"The budget was allocated to each department.", exJa:"予算は各部署に割り当てられた。", tip:"allocate A to B＝AをBに割り当てる。allocation＝配分。", lv:3},
  {w:"compensate", m:"補償する、埋め合わせる", ex:"The airline compensated passengers for the delay.", exJa:"航空会社は遅延について乗客に補償した。", tip:"compensate A for B＝AにBの補償をする。compensation＝補償金・報酬。", lv:3},
  {w:"anticipate", m:"予期する、見込む", ex:"We anticipate strong demand for the new model.", exJa:"新モデルには高い需要が見込まれる。", tip:"expectのフォーマル版。larger than anticipated＝予想以上の。", lv:3},
  {w:"designate", m:"指定する、任命する", ex:"The area is designated for visitor parking.", exJa:"その区画は来客用駐車場に指定されている。", tip:"designated smoking area＝指定喫煙所。人の「任命」にも使う。", lv:3},
  {w:"mandatory", m:"義務的な、必須の", ex:"Attendance at the training is mandatory.", exJa:"研修への出席は必須です。", tip:"required／compulsoryと同義。⇔optional（任意の）。社内通知で頻出。", lv:3},
  {w:"eligible", m:"資格のある", ex:"Full-time employees are eligible for the benefits.", exJa:"正社員はその福利厚生を受ける資格がある。", tip:"be eligible for 〜＝の資格がある。eligibility＝適格性。", lv:3},
  {w:"preliminary", m:"予備の、準備段階の", ex:"The preliminary results will be announced tomorrow.", exJa:"予備調査の結果は明日発表される。", tip:"pre（前の）が語源。preliminary meeting＝事前会議。本番前の「予備段階」。", lv:3},
  {w:"subsequent", m:"その後の", ex:"Details will be provided in subsequent emails.", exJa:"詳細は追ってメールでお知らせします。", tip:"subsequently＝その後。⇔previous（前の）。", lv:3},
  {w:"prior", m:"（〜より）前の、事前の", ex:"Prior approval is required for overtime.", exJa:"残業には事前の承認が必要です。", tip:"prior to 〜＝より前に（beforeのフォーマル版）。prior experience＝これまでの経験。", lv:3},
  {w:"comprehensive", m:"包括的な、総合的な", ex:"The report gives a comprehensive overview of the market.", exJa:"その報告書は市場の包括的な概要を示している。", tip:"comprehensive insurance＝総合保険。「全部入り」のイメージ。", lv:3},
  {w:"substantial", m:"かなりの、相当な", ex:"The company made a substantial investment in research.", exJa:"会社は研究に相当な投資をした。", tip:"substantial increase＝大幅な増加。considerableと同義。", lv:3},
  {w:"adequate", m:"十分な、適切な", ex:"The room has adequate space for ten people.", exJa:"その部屋には10人分の十分な広さがある。", tip:"「必要を満たすだけの」。⇔inadequate（不十分な）。", lv:3},
  {w:"exceed", m:"（限度・予想を）超える", ex:"Sales exceeded expectations this quarter.", exJa:"今四半期の売上は予想を上回った。", tip:"ex（外へ）+ ceed（行く）。exceed the limit＝制限を超える。", lv:3},
  {w:"fluctuate", m:"変動する", ex:"Prices fluctuate depending on the season.", exJa:"価格は季節によって変動する。", tip:"上下に揺れ動くイメージ。fluctuation＝変動。為替・株価の話題で登場。", lv:3},
  {w:"diversify", m:"多様化する", ex:"The company plans to diversify its product line.", exJa:"会社は製品ラインの多様化を計画している。", tip:"diverse（多様な）+ ify。事業多角化の文脈で頻出。diversity＝多様性。", lv:3},
  {w:"acquisition", m:"（企業）買収、取得", ex:"The acquisition of the startup was announced Monday.", exJa:"そのスタートアップの買収は月曜に発表された。", tip:"acquire（獲得する）の名詞。M&A＝mergers and acquisitions。", lv:3},
  {w:"subsidiary", m:"子会社", ex:"The firm has subsidiaries in five countries.", exJa:"その会社は5か国に子会社を持つ。", tip:"parent company（親会社）とセットで覚える。", lv:3},
  {w:"entrepreneur", m:"起業家", ex:"The magazine features successful entrepreneurs.", exJa:"その雑誌は成功した起業家を特集している。", tip:"フランス語由来。発音は「アントレプレナー」。entrepreneurship＝起業家精神。", lv:3},
  {w:"commemorate", m:"記念する", ex:"A ceremony was held to commemorate the founding.", exJa:"創立を記念して式典が開かれた。", tip:"com + memor（記憶）。in commemoration of 〜＝を記念して。周年行事で登場。", lv:3},
  {w:"prestigious", m:"名声のある、一流の", ex:"She graduated from a prestigious university.", exJa:"彼女は名門大学を卒業した。", tip:"prestige（名声）+ ous。prestigious award＝権威ある賞。", lv:3},
  {w:"state-of-the-art", m:"最新式の", ex:"The factory uses state-of-the-art technology.", exJa:"その工場は最新鋭の技術を使っている。", tip:"「芸術の域の状態」→最新式。the latest／cutting-edgeと同義。", lv:3},
  {w:"durable", m:"耐久性のある", ex:"These boots are durable and waterproof.", exJa:"このブーツは丈夫で防水だ。", tip:"dur（続く）+ able。durability＝耐久性。商品説明文で頻出。", lv:3},
  {w:"defective", m:"欠陥のある", ex:"Defective items can be returned for free.", exJa:"欠陥品は無料で返品できます。", tip:"defect（欠陥）+ ive。defective product＝不良品。返品・交換の文脈で頻出。", lv:3},
  {w:"malfunction", m:"故障（する）", ex:"The copier malfunctioned during the meeting.", exJa:"会議中にコピー機が故障した。", tip:"mal（悪い）+ function（機能）。機器トラブルの話題（Part 3）で登場。", lv:3},
  {w:"overdue", m:"（支払いが）延滞している", ex:"Your payment is now 30 days overdue.", exJa:"お支払いは30日超過しています。", tip:"over + due（期限）。督促状（Part 7）の定番語。long overdue＝待たれて久しい。", lv:3},
  {w:"outstanding", m:"傑出した、未払いの", ex:"You have an outstanding balance of 5,000 yen.", exJa:"未払い残高が5,000円あります。", tip:"「目立って立っている」→傑出。請求書の文脈ではほぼ「未払いの」。", lv:3},
  {w:"quota", m:"ノルマ、割当量", ex:"The sales team met its monthly quota.", exJa:"営業チームは月間ノルマを達成した。", tip:"meet／fill a quota＝ノルマを達成する。輸入割当などにも使う。", lv:3},
  {w:"surplus", m:"余剰、黒字", ex:"The company reported a budget surplus.", exJa:"会社は予算の黒字を報告した。", tip:"sur（超えて）+ plus。⇔deficit。surplus inventory＝余剰在庫。", lv:3},
  {w:"deficit", m:"赤字、不足", ex:"The city is facing a budget deficit.", exJa:"市は財政赤字に直面している。", tip:"trade deficit＝貿易赤字。⇔surplus（黒字・余剰）。", lv:3},
  {w:"attain", m:"（目標を）達成する", ex:"She attained her sales goal ahead of schedule.", exJa:"彼女は予定より早く販売目標を達成した。", tip:"attain a goal＝目標を達成する。achieveのフォーマル版。", lv:3},
  {w:"facilitate", m:"円滑にする、促進する", ex:"The new system will facilitate communication.", exJa:"新システムは意思疎通を円滑にする。", tip:"facile（容易な）から。会議のfacilitator＝進行役。", lv:3},
  {w:"impede", m:"妨げる、遅らせる", ex:"Bad weather impeded the construction work.", exJa:"悪天候が建設作業を妨げた。", tip:"im（中に）+ ped（足）→足かせをはめる。hinderと同義。⇔facilitate。", lv:3},
  {w:"curtail", m:"削減する、切り詰める", ex:"The company curtailed travel expenses.", exJa:"会社は出張費を削減した。", tip:"cut（切る）のイメージで「切り詰める」。curtail spending＝支出を削減する。", lv:3},
];
